'use strict';
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
let W=innerWidth,H=innerHeight,DPR=Math.min(devicePixelRatio||1,2);
function resize(){W=innerWidth;H=innerHeight;canvas.width=W*DPR;canvas.height=H*DPR;ctx.setTransform(DPR,0,0,DPR,0,0)}addEventListener('resize',resize);resize();
const keys={up:false,down:false,left:false,right:false};
const player={x:0,y:35,a:0,health:100,money:0,wanted:0,car:-1};
const cars=[{x:12,y:25,a:Math.PI},{x:-12,y:25,a:0},{x:25,y:-18,a:Math.PI/2},{x:-25,y:-20,a:-Math.PI/2}];
let mission={x:55,y:55},bullets=[],last=performance.now();
const colors=['#b9a48a','#8b9bab','#c47d62','#8caa7d','#b4b4b4','#d1a35f'];
const buildings=[];
for(let x=-220;x<=220;x+=35)for(let y=-220;y<=220;y+=35){if(Math.abs(x)<15||Math.abs(y)<15||Math.abs(Math.abs(x)-80)<10||Math.abs(Math.abs(y)-80)<10)continue;buildings.push({x:x+(Math.random()-.5)*7,y:y+(Math.random()-.5)*7,w:20,h:10+Math.random()*28,d:20,c:colors[(Math.random()*colors.length)|0]})}
function bind(id,k){let b=document.getElementById(id);if(!b)return;for(const ev of ['touchstart','mousedown'])b.addEventListener(ev,e=>{e.preventDefault();keys[k]=true},{passive:false});for(const ev of ['touchend','mouseup','mouseleave'])b.addEventListener(ev,e=>{e.preventDefault();keys[k]=false},{passive:false})}bind('up','up');bind('down','down');bind('left','left');bind('right','right');
addEventListener('keydown',e=>{if(e.key==='w'||e.key==='ArrowUp')keys.up=true;if(e.key==='s'||e.key==='ArrowDown')keys.down=true;if(e.key==='a'||e.key==='ArrowLeft')keys.left=true;if(e.key==='d'||e.key==='ArrowRight')keys.right=true;if(e.code==='Space')shoot()});addEventListener('keyup',e=>{if(e.key==='w'||e.key==='ArrowUp')keys.up=false;if(e.key==='s'||e.key==='ArrowDown')keys.down=false;if(e.key==='a'||e.key==='ArrowLeft')keys.left=false;if(e.key==='d'||e.key==='ArrowRight')keys.right=false});
function shoot(){let a=player.a;bullets.push({x:player.x,y:player.y,vx:Math.sin(a)*3.2,vy:-Math.cos(a)*3.2,life:70});player.wanted=Math.min(5,player.wanted+1)}document.getElementById('shoot').addEventListener('click',shoot);document.getElementById('shoot').addEventListener('touchstart',e=>{e.preventDefault();shoot()},{passive:false});
document.getElementById('enter').addEventListener('click',()=>{if(player.car<0){let best=-1,bd=5;cars.forEach((c,i)=>{let d=Math.hypot(c.x-player.x,c.y-player.y);if(d<bd){bd=d;best=i}});if(best>=0){player.car=best;player.x=cars[best].x;player.y=cars[best].y}}else{player.car=-1}});
function move(dt){let turn=(keys.left?-1:0)+(keys.right?1:0);player.a+=turn*2.4*dt;let speed=(keys.up?7:0)+(keys.down?-5:0);if(player.car>=0){let c=cars[player.car];c.a=player.a;speed=(keys.up?13:0)+(keys.down?-8:0);c.x+=Math.sin(c.a)*speed*dt;c.y+=-Math.cos(c.a)*speed*dt;player.x=c.x;player.y=c.y}else{player.x+=Math.sin(player.a)*speed*dt;player.y+=-Math.cos(player.a)*speed*dt}}
function project(wx,wy,depth){const dx=wx-player.x,dy=wy-player.y;const ca=Math.cos(player.a),sa=Math.sin(player.a);const z=dx*sa+dy*(-ca),side=dx*ca+dy*sa;if(z<1)return null;const f=Math.min(W,H)*.9;return{x:W/2+side*f/z,y:H*.52-z*0.12,s:f/z,z}}
function drawRoads(){ctx.fillStyle='#4e7f46';ctx.fillRect(0,0,W,H);const lines=[['v',0,20],['v',80,12],['v',-80,12],['h',0,20],['h',80,12],['h',-80,12]];for(const [t,p,w] of lines){for(let i=0;i<50;i++){let a=-250+i*10,b=a+10;if(t==='v'){let p1=project(p,a,0),p2=project(p,b,0);if(p1&&p2){ctx.strokeStyle='#303030';ctx.lineWidth=Math.max(2,Math.min(50,Math.abs(p1.y-p2.y)));ctx.beginPath();ctx.moveTo(p1.x,p1.y);ctx.lineTo(p2.x,p2.y);ctx.stroke()}}else{let p1=project(a,p,0),p2=project(b,p,0);if(p1&&p2){ctx.strokeStyle='#303030';ctx.lineWidth=Math.max(2,Math.min(50,Math.abs(p1.y-p2.y)));ctx.beginPath();ctx.moveTo(p1.x,p1.y);ctx.lineTo(p2.x,p2.y);ctx.stroke()}}}}}
function drawBuildings(){let arr=buildings.map(b=>{let dx=b.x-player.x,dy=b.y-player.y;return{b,z:Math.hypot(dx,dy)}}).sort((a,b)=>b.z-a.z);for(const {b} of arr){let p=project(b.x,b.y,0);if(!p)continue;let s=Math.max(2,Math.min(220,p.s*b.w));let h=Math.max(3,Math.min(H*.7,p.s*b.h));ctx.fillStyle=b.c;ctx.fillRect(p.x-s/2,p.y-h,s,h);ctx.fillStyle='#ffffff55';for(let yy=p.y-h+8;yy<p.y-4;yy+=12)for(let xx=p.x-s/2+5;xx<p.x+s/2-4;xx+=10)ctx.fillRect(xx,yy,5,6)}}
function drawCar(c,i){let p=project(c.x,c.y,0);if(!p)return;let s=Math.max(4,Math.min(70,p.s*2.8));ctx.save();ctx.translate(p.x,p.y);ctx.rotate(c.a-player.a);ctx.fillStyle=['#d22','#ddc51f','#28a86b','#3675d5'][i];ctx.fillRect(-s/2,-s,s,s*1.7);ctx.fillStyle='#222';ctx.fillRect(-s*.34,-s*.78,s*.68,s*.42);ctx.restore()}
function drawPlayer(){if(player.car>=0)return;let p=project(player.x,player.y,0);if(!p)return;let s=Math.max(5,Math.min(35,p.s));ctx.fillStyle='#2266cc';ctx.fillRect(p.x-s/2,p.y-s,s,s*1.3);ctx.fillStyle='#d49a72';ctx.beginPath();ctx.arc(p.x,p.y-s*1.1,s*.38,0,Math.PI*2);ctx.fill()}
function drawMarker(){let p=project(mission.x,mission.y,0);if(!p)return;let r=Math.max(6,Math.min(40,p.s*3));ctx.strokeStyle='#ffd400';ctx.lineWidth=4;ctx.beginPath();ctx.arc(p.x,p.y,r,0,Math.PI*2);ctx.stroke()}
function drawBullets(){ctx.fillStyle='#ff0';for(const b of bullets){let p=project(b.x,b.y,0);if(p)ctx.beginPath(),ctx.arc(p.x,p.y,3,0,Math.PI*2),ctx.fill()}}
function update(dt){move(dt);if(player.car<0){player.x=Math.max(-245,Math.min(245,player.x));player.y=Math.max(-245,Math.min(245,player.y))}for(let i=bullets.length-1;i>=0;i--){let b=bullets[i];b.x+=b.vx;b.y+=b.vy;b.life--;if(b.life<=0)bullets.splice(i,1);else for(const c of cars)if(Math.hypot(c.x-b.x,c.y-b.y)<2.5){player.money+=10;bullets.splice(i,1);break}}if(Math.hypot(player.x-mission.x,player.y-mission.y)<6){player.money+=100;mission={x:(Math.random()-.5)*180,y:(Math.random()-.5)*180};document.getElementById('mission').textContent='Mission complete! +₹100'}else document.getElementById('mission').textContent='Mission: reach the yellow marker';document.getElementById('health').textContent=player.health;document.getElementById('money').textContent=player.money;document.getElementById('wanted').textContent=player.wanted}
function render(){ctx.clearRect(0,0,W,H);let g=ctx.createLinearGradient(0,0,0,H*.55);g.addColorStop(0,'#86bce8');g.addColorStop(1,'#d8ecf7');ctx.fillStyle=g;ctx.fillRect(0,0,W,H*.55);drawRoads();drawBuildings();cars.forEach(drawCar);drawMarker();drawBullets();drawPlayer()}
function loop(t){let dt=Math.min(.05,(t-last)/1000);last=t;update(dt);render();requestAnimationFrame(loop)}requestAnimationFrame(loop);
